version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    command: ["uvicorn", "app:app", "--host", "0.0.0.0", "--port", "8000", "--reload"]
    env_file:
      - backend/.local.env
    privileged: true
    volumes:
      - ./backend:/backend
    ports:
      - 8000:8000
